version: '3.1'

services:
  db:
    image: mysql:8.0.30-debian
    restart: always
    ports:
      - 3306:3306
    # volumes:  Z:\database\ecommerce
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin